### ISSUE TITLE
Timing report doesn't show parallel time for internal parallel loop

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#2597] opened 2022-02-08 01:16 UTC
Take IMConstProp or LowerTypes, for instance.  These both have internal parallel loops, but the pass timing reports are not aware of this as the appropriate per-thread timers for the pass are never started.

**Comment by dtzSiFive** [comment] 2023-06-05 15:48
Dupe of #1308.

**Closed by dtzSiFive** 2023-06-05 15:48 UTC
