### ISSUE TITLE
[ExportVerilog] [Integration Tests] Naming broken and crashes

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#863] opened 2021-03-31 21:31 UTC
One (or more) of today's verilog emission commits broke the integration tests. This showed up in the ESI integration tests, but I think that's only because they are the most comprehensive and/or use ExportVerilog differently than FIRRTL. It broke 4 tests total (one unit test, 3 integration tests), but I'm only including the lit output from two which are representative of the other failures.

```
FAIL: CIRCT :: ESI/system/basic.mlir (1 of 14)
******************** TEST 'CIRCT :: ESI/system/basic.mlir' FAILED ********************
Script:
--
: 'RUN: at line 2';   /home/jodemme/circt/build/bin/circt-opt /home/jodemme/circt/integration_test/ESI/system/basic.mlir --lower-esi-to-physical --lower-esi-ports --lower-esi-to-rtl -verify-diagnostics > /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp1.mlir
: 'RUN: at line 3';   /home/jodemme/circt/build/bin/circt-translate /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp1.mlir -export-verilog -verify-diagnostics > /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv
: 'RUN: at line 4';   /home/jodemme/circt/build/bin/circt-rtl-sim.py /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv /home/jodemme/circt/include/circt/Dialect/ESI/ESIPrimitives.sv /home/jodemme/circt/integration_test/ESI/system/../supplements/integers.sv --cycles 150 | /home/jodemme/circt/llvm/build/bin/FileCheck /home/jodemme/circt/integration_test/ESI/system/basic.mlir
--
Exit Code: 2

Command Output (stderr):
--
%Warning-WIDTH: /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv:55:15: Operator ASSIGNW expects 32 bits on the Assign RHS, but Assign RHS's VARREF '_T_5' generates 1 bits.
                                                                                                     : ... In instance top
   55 |   assign _T_4 = _T_5;
      |               ^
                ... Use "/* verilator lint_off WIDTH */" and lint_on around source to disable this message.
%Warning-WIDTH: /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv:56:15: Operator ASSIGNW expects 1 bits on the Assign RHS, but Assign RHS's VARREF '_T_4' generates 32 bits.
                                                                                                     : ... In instance top
   56 |   assign _T_3 = _T_4;
      |               ^
%Warning-WIDTH: /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv:62:6: Input port connection 'a' expects 32 bits on the pin connection, but pin connection's VARREF '_T_3' generates 1 bits.
                                                                                                    : ... In instance top
   62 |     .a       (_T_3),
      |      ^
%Warning-WIDTH: /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv:70:15: Operator ASSIGNW expects 32 bits on the Assign RHS, but Assign RHS's VARREF '_T_2' generates 1 bits.
                                                                                                     : ... In instance top
   70 |   assign _T_1 = _T_2;
      |               ^
%Warning-WIDTH: /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv:71:15: Operator ASSIGNW expects 1 bits on the Assign RHS, but Assign RHS's VARREF '_T_1' generates 32 bits.
                                                                                                     : ... In instance top
   71 |   assign _T_0 = _T_1;
      |               ^
%Warning-WIDTH: /home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv:74:20: Operator ASSIGNW expects 32 bits on the Assign RHS, but Assign RHS's VARREF '_T_0' generates 1 bits.
                                                                                                     : ... In instance top
   74 |   assign _T_7.data = _T_0;
      |                    ^
%Error: Exiting due to 6 warning(s)
CompletedProcess(args=['/home/jodemme/circt/ext/bin/verilator', '--cc', '--top-module', 'top', '-sv', '--build', '--exe', '--Mdir', 'basic.mlir.tmp2.sv.obj_dir', '--assert', '/home/jodemme/circt/build/integration_test/ESI/system/Output/basic.mlir.tmp2.sv', '/home/jodemme/circt/include/circt/Dialect/ESI/ESIPrimitives.sv', '/home/jodemme/circt/integration_test/ESI/system/../supplements/integers.sv', '/home/jodemme/circt/build/bin/driver.cpp'], returncode=1)
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/jodemme/circt/llvm/build/bin/FileCheck /home/jodemme/circt/integration_test/ESI/system/basic.mlir

--
```

```
********************
FAIL: CIRCT :: ESI/cosim/basic.mlir (7 of 14)
******************** TEST 'CIRCT :: ESI/cosim/basic.mlir' FAILED ********************
Script:
--
: 'RUN: at line 2';   /home/jodemme/circt/build/bin/circt-opt /home/jodemme/circt/integration_test/ESI/cosim/basic.mlir --lower-esi-to-physical --lower-esi-ports --lower-esi-to-rtl | /home/jodemme/circt/build/bin/circt-translate --export-verilog > /home/jodemme/circt/build/integration_test/ESI/cosim/Output/basic.mlir.tmp1.sv
: 'RUN: at line 3';   /home/jodemme/circt/build/bin/circt-translate /home/jodemme/circt/integration_test/ESI/cosim/basic.mlir -export-esi-capnp -verify-diagnostics > /home/jodemme/circt/build/integration_test/ESI/cosim/Output/basic.mlir.tmp2.capnp
: 'RUN: at line 4';   /home/jodemme/circt/build/bin/esi-cosim-runner.py --schema /home/jodemme/circt/build/integration_test/ESI/cosim/Output/basic.mlir.tmp2.capnp /home/jodemme/circt/integration_test/ESI/cosim/basic.mlir /home/jodemme/circt/build/integration_test/ESI/cosim/Output/basic.mlir.tmp1.sv /home/jodemme/circt/integration_test/ESI/cosim/../supplements/integers.sv
--
Exit Code: 134

Command Output (stderr):
--
<unknown>:0: error: invalid element for rtl.inout type
circt-translate: /home/jodemme/circt/llvm/mlir/include/mlir/IR/StorageUniquerSupport.h:96: static ConcreteT mlir::detail::StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits>::get(mlir::MLIRContext*, Args ...) [with Args = {mlir::Type}; ConcreteT = circt::rtl::InOutType; BaseT = mlir::Type; StorageT = circt::rtl::detail::InOutTypeStorage; UniquerT = mlir::detail::TypeUniquer; Traits = {}]: Assertion `succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/jodemme/circt/build/bin/circt-translate --export-verilog
 #0 0x00007fe1524db6ea llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/jodemme/circt/llvm/llvm/lib/Support/Unix/Signals.inc:565:11
 #1 0x00007fe1524db8bb PrintStackTraceSignalHandler(void*) /home/jodemme/circt/llvm/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x00007fe1524d9e8b llvm::sys::RunSignalHandlers() /home/jodemme/circt/llvm/llvm/lib/Support/Signals.cpp:70:5
 #3 0x00007fe1524dc031 SignalHandler(int) /home/jodemme/circt/llvm/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007fe151d75d60 (/lib/x86_64-linux-gnu/libc.so.6+0x3bd60)
 #5 0x00007fe151d75ce1 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007fe151d5f537 abort ./stdlib/abort.c:81:7
 #7 0x00007fe151d5f40f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #8 0x00007fe151d5f40f _nl_load_domain ./intl/loadmsgcat.c:970:34
 #9 0x00007fe151d6e662 (/lib/x86_64-linux-gnu/libc.so.6+0x34662)
#10 0x00007fe151a64f29 circt::rtl::InOutType mlir::detail::StorageUserBase<circt::rtl::InOutType, mlir::Type, circt::rtl::detail::InOutTypeStorage, mlir::detail::TypeUniquer>::get<mlir::Type>(mlir::MLIRContext*, mlir::Type) /home/jodemme/circt/llvm/mlir/include/mlir/IR/StorageUniquerSupport.h:96:5
#11 0x00007fe151a606c3 circt::rtl::InOutType::get(mlir::MLIRContext*, mlir::Type) /home/jodemme/circt/build/include/circt/Dialect/RTL/RTLTypes.cpp.inc:147:1
#12 0x00007fe151d10532 circt::rtl::InOutType::get(mlir::Type) /home/jodemme/circt/build/include/circt/Dialect/RTL/RTLTypes.h.inc:66:5
#13 0x00007fe151ce744d circt::sv::WireOp::build(mlir::OpBuilder&, mlir::OperationState&, mlir::Type, mlir::StringAttr) /home/jodemme/circt/lib/Dialect/SV/SVOps.cpp:835:47
#14 0x00007fe1525a8d79 circt::sv::WireOp mlir::OpBuilder::create<circt::sv::WireOp, mlir::Type>(mlir::Location, mlir::Type&&) /home/jodemme/circt/llvm/mlir/include/mlir/IR/Builders.h:399:31
#15 0x00007fe1525a3dcb circt::sv::WireOp mlir::ImplicitLocOpBuilder::create<circt::sv::WireOp, mlir::Type>(mlir::Type&&) /home/jodemme/circt/llvm/mlir/include/mlir/IR/ImplicitLocOpBuilder.h:68:3
#16 0x00007fe15258b6ca lowerUsersToTemporaryWire(mlir::Operation&) /home/jodemme/circt/lib/Translation/ExportVerilog/ExportVerilog.cpp:2503:59
#17 0x00007fe15258bd64 (anonymous namespace)::ModuleEmitter::prepareRTLModule(mlir::Block&) /home/jodemme/circt/lib/Translation/ExportVerilog/ExportVerilog.cpp:2598:32
#18 0x00007fe15258be9a (anonymous namespace)::ModuleEmitter::emitRTLModule(circt::rtl::RTLModuleOp) /home/jodemme/circt/lib/Translation/ExportVerilog/ExportVerilog.cpp:2608:58
#19 0x00007fe15258c9ed (anonymous namespace)::UnifiedEmitter::emitMLIRModule() /home/jodemme/circt/lib/Translation/ExportVerilog/ExportVerilog.cpp:2777:7
#20 0x00007fe15258d669 circt::exportVerilog(mlir::ModuleOp, llvm::raw_ostream&) /home/jodemme/circt/lib/Translation/ExportVerilog/ExportVerilog.cpp:2911:42
#21 0x00007fe1527683c5 mlir::LogicalResult std::__invoke_impl<mlir::LogicalResult, mlir::LogicalResult (*&)(mlir::ModuleOp, llvm::raw_ostream&), mlir::ModuleOp, llvm::raw_ostream&>(std::__invoke_other, mlir::LogicalResult (*&)(mlir::ModuleOp, llvm::raw_ostream&), mlir::ModuleOp&&, llvm::raw_ostream&) /usr/include/c++/10/bits/invoke.h:60:70
#22 0x00007fe152767e30 _ZSt10__invoke_rIN4mlir13LogicalResultERPFS1_NS0_8ModuleOpERN4llvm11raw_ostreamEEJS2_S5_EENSt9enable_ifIXsrSt6__and_IJSt6__not_ISt7is_voidIT_EESt14is_convertibleINSt15__invoke_resultIT0_JDpT1_EE4typeESD_EEE5valueESD_E4typeEOSI_DpOSJ_ /usr/include/c++/10/bits/invoke.h:143:5
#23 0x00007fe1527677f9 std::_Function_handler<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&), mlir::LogicalResult (*)(mlir::ModuleOp, llvm::raw_ostream&)>::_M_invoke(std::_Any_data const&, mlir::ModuleOp&&, llvm::raw_ostream&) /usr/include/c++/10/bits/std_function.h:293:7
#24 0x00007fe152531090 std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)>::operator()(mlir::ModuleOp, llvm::raw_ostream&) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14
#25 0x00007fe15252ab00 mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(llvm::StringRef, std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)> const&, std::function<void (mlir::DialectRegistry&)>)::$_1::operator()(llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*) const /home/jodemme/circt/llvm/mlir/lib/Translation/Translation.cpp:107:12
#26 0x00007fe15252aa1c mlir::LogicalResult std::__invoke_impl<mlir::LogicalResult, mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(llvm::StringRef, std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)> const&, std::function<void (mlir::DialectRegistry&)>)::$_1&, llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*>(std::__invoke_other, mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(llvm::StringRef, std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)> const&, std::function<void (mlir::DialectRegistry&)>)::$_1&, llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14
#27 0x00007fe15252a98c std::enable_if<__and_<std::__not_<std::is_void<mlir::LogicalResult> >, std::is_convertible<std::__invoke_result<mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(llvm::StringRef, std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)> const&, std::function<void (mlir::DialectRegistry&)>)::$_1&, llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*>::type, mlir::LogicalResult> >::value, mlir::LogicalResult>::type std::__invoke_r<mlir::LogicalResult, mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(llvm::StringRef, std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)> const&, std::function<void (mlir::DialectRegistry&)>)::$_1&, llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*>(mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(llvm::StringRef, std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)> const&, std::function<void (mlir::DialectRegistry&)>)::$_1&, llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:141:14
#28 0x00007fe15252a7ec std::_Function_handler<mlir::LogicalResult (llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*), mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(llvm::StringRef, std::function<mlir::LogicalResult (mlir::ModuleOp, llvm::raw_ostream&)> const&, std::function<void (mlir::DialectRegistry&)>)::$_1>::_M_invoke(std::_Any_data const&, llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:291:9
#29 0x00007fe15252dbf5 std::function<mlir::LogicalResult (llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*)>::operator()(llvm::SourceMgr&, llvm::raw_ostream&, mlir::MLIRContext*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14
#30 0x00007fe152529a2f mlir::mlirTranslateMain(int, char**, llvm::StringRef)::$_3::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&) const /home/jodemme/circt/llvm/mlir/lib/Translation/Translation.cpp:188:14
#31 0x00007fe15252980d mlir::mlirTranslateMain(int, char**, llvm::StringRef) /home/jodemme/circt/llvm/mlir/lib/Translation/Translation.cpp:203:21
#32 0x000055ad5c7b1f66 main /home/jodemme/circt/tools/circt-translate/circt-translate.cpp:20:22
#33 0x00007fe151d60d0a __libc_start_main ./csu/../csu/libc-start.c:308:16
#34 0x000055ad5c7b1e6a _start (/home/jodemme/circt/build/bin/circt-translate+0x1e6a)
/home/jodemme/circt/build/integration_test/ESI/cosim/Output/basic.mlir.script: line 3: 27275 Done                    /home/jodemme/circt/build/bin/circt-opt /home/jodemme/circt/integration_test/ESI/cosim/basic.mlir --lower-esi-to-physical --lower-esi-ports --lower-esi-to-rtl
     27277 Aborted                 | /home/jodemme/circt/build/bin/circt-translate --export-verilog > /home/jodemme/circt/build/integration_test/ESI/cosim/Output/basic.mlir.tmp1.sv

--
```

**Comment by lattner** [comment] 2021-03-31 22:07
The crash was [fixed already](https://github.com/llvm/circt/commit/8dce8f882ec2069fa7695f623c678894b3fd19f0).  The other is an expected change in the generated verilog.  Incidentally, the generated verilog is going to continue to change, I think the integration test is just going to be super fragile over time.

**Comment by seldridge** [comment] 2021-03-31 22:19
The first issue may actually be a regression and not just a Verilog change. Naked connections without padding/slices is probably bad and most linters will yell at you.

@Ramlakshmi3733 noticed something very similar to this and I expect it's the same issue. Roughly he was seeing a tower of assigns with a lot of weird widths and some downstream user doing an invalid bit slice off it:

```verilog
wire [7:0] _T_0;
wire [3:0] _T_1;
wire _T_2;
wire _T_3;

assign _T_1 = _T_0;
assign _T_2 = _T_1;
assign _T_3 = _T_2;

wire [2:0] foo = _T_3[2:0];
```

**Comment by teqdruid** [comment] 2021-03-31 22:27
> The crash was [fixed already](https://github.com/llvm/circt/commit/8dce8f882ec2069fa7695f623c678894b3fd19f0). The other is an expected change in the generated verilog. Incidentally, the generated verilog is going to continue to change, I think the integration test is just going to be super fragile over time.

I'm running a version with that patch.

Why would the integration test be super fragile? It doesn't check the verilog output, just runs it in Verilator. Anytime Verilator refuses to compile it, that's a pretty good indication that something's wrong with the output that's not just a NFC. You're right about the unit tests which check the SV output. I've been whittling them down to key things which should always appear in the output.

**Comment by lattner** [comment] 2021-03-31 22:38
Ok, I'm super happy to look at this, but I don't have all the dependencies installed.  Trying something simple isn't working, any hints?

```
$ cd integration_test/ESI/cosim
$ circt-opt basic.mlir --lower-esi-to-physical --lower-esi-ports --lower-esi-to-rtl | circt-translate -export-verilog
basic.mlir:15:13: error: failed to legalize operation 'esi.cosim' that was explicitly marked illegal
  %intsIn = esi.cosim %clk, %rstn, %intsTotalBuffered, 1 {name="TestEP"} : !esi.channel<i32> -> !esi.channel<i32>
            ^
basic.mlir:15:13: note: see current operation: %0 = "esi.cosim"(%clk, %rstn, %chanOutput_14) {endpointID = 1 : i64, name = "TestEP"} : (i1, i1, !esi.channel<i32>) -> !esi.channel<i32>

```

**Comment by teqdruid** [comment] 2021-03-31 23:05
Yeah, that's not the nicest error but expected in a non-capnp build.

We've got two options:
- You could use Docker to build and run with all the deps. (This would be useful for more than this specific case.) Docker on Mac doesn't seem difficult to install: https://docs.docker.com/docker-for-mac/install/ then we've got a script under utils/ to build and run everything in Docker, caching all of it.
- I could generate a sv/rtl/comb only integration test from the ESI ones. (I'll do this.)

The first test I posted 'integration_tests/ESI/system/basic.mlir' shouldn't require capnp.

**Comment by teqdruid** [comment] 2021-03-31 23:12
[testcase.zip](https://github.com/llvm/circt/files/6239990/testcase.zip)

This is a testcase which repros the crash when run through `circt-translate --export-verilog testcase.mlir`. (Sorry, github doesn't support .mlir attachments.)

**Comment by teqdruid** [comment] 2021-04-01 00:19
[testcase.mlir.txt](https://github.com/llvm/circt/files/6240172/testcase.mlir.txt)

Here's a more condensed testcase for the crash bug.

**Comment by lattner** [comment] 2021-04-01 00:23
Weird, looks like array types aren't allowed in inout's.  That seems like a bad thing.

**Comment by teqdruid** [comment] 2021-04-01 00:24
I'm not familiar with the changes, but why does `inout` get used at all? It's not used in the testcase I provided.

**Comment by lattner** [comment] 2021-04-01 00:26
It's arrays of si8 specifically.

This is because the Verilog emitter is emitting temporary wires to avoid cyclic reference issues.

**Comment by lattner** [comment] 2021-04-01 00:35
The crash is fixed in 29cdb670.  I'd love help with the other issue, even just with the repro side of it.

**Comment by lattner** [comment] 2021-04-01 00:36
I'd love the output of the circt-opt command above, just something I can shove into 'translate' to get the verilog.  I don't think that will have any deps on other things.

**Comment by lattner** [comment] 2021-04-01 00:40
actually, I think I understand what is going on.  Definitely my fault.  Working on it.

**Comment by lattner** [comment] 2021-04-01 00:51
I think the correctness problem is fixed here, thank you for the testcases, I really appreciate it!
d9c34092

**Comment by teqdruid** [comment] 2021-04-01 00:51
[testcase_2.mlir.txt](https://github.com/llvm/circt/files/6240235/testcase_2.mlir.txt)

**Closed by lattner** 2021-04-01 00:51 UTC
Labels: ExportVerilog, bug

**Comment by teqdruid** [comment] 2021-04-01 00:53
Fix confirmed! Thank you @lattner !
