### ISSUE TITLE
How can I lower calyx dialect to a unified, low-level dialect, I may have some question.

### ISSUE THREAD

**Issue by linuxlonelyeagle** [llvm/circt#5296] opened 2023-05-31 06:33 UTC
I am learning the calyx dialect.I know calyx can be lowered to fsm dialect by the picture of lower's route inside the official documentation.
```
// Here is my code.
module attributes {calyx.entrypoint = "main"} { 
calyx.component @identity(%in: i32, %go: i1 {go}, %clk: i1 {clk}, %reset: i1 {reset}) -> (%out: i32, %done: i1 {done}) {
  %r.in, %r.write_en, %r.clk, %r.reset, %r.out, %r.done = calyx.register @r : i32, i1, i1, i1, i32, i1
  %c1_1 = hw.constant 1 : i1
  %true = hw.constant true
  calyx.wires {
    calyx.group @save {
      calyx.assign %r.in = %in : i32 
      calyx.assign %r.write_en = %c1_1 : i1 
      calyx.group_done %r.done : i1
   } 
    calyx.assign %out = %r.out :i32
  }

  calyx.control {
    calyx.seq {
      calyx.enable @save
    }
 }
}

calyx.component @main(%go: i1 {go}, %clk: i1 {clk}, %reset: i1 {reset}) -> (%done: i1 {done}) {
  %id.in, %id.go, %id.clk, %id.reset, %id.out, %id.done = calyx.instance @id of @identity : i32, i1, i1, i1, i32, i1
  %r.in, %r.write_en, %r.clk, %r.reset, %r.out, %r.done = calyx.register @r : i32, i1, i1, i1, i32, i1 
  %c1_1 = hw.constant 1 : i1
  %c1_10 = hw.constant 10 : i32

  calyx.wires {
    calyx.group @run_id {
      calyx.assign %id.in = %c1_10 : i32
      calyx.assign %id.go = %c1_1 : i1
      calyx.group_done %id.done : i1
    }

    calyx.group @use_id {
      calyx.assign %r.in = %id.out : i32
      calyx.assign %r.write_en = %c1_1: i1
      calyx.group_done %r.done: i1
    }
  }

  calyx.control {
    calyx.seq {
      calyx.enable @use_id
      calyx.enable @run_id
    }
  }
}
}
```
I found a problem that I just can lower the calyx dialect to the fsm, which prevented me from lowering it further.
```
circt-opt calyx.mlir -lower-calyx-to-fsm -materialize-calyx-to-fsm -calyx-remove-groups-fsm  -lower-calyx-to-hw
calyx.mlir:42:3: error: mismatch in number of types compared (2 != 3)
  calyx.control {
  ^
calyx.mlir:42:3: error: 'fsm.hw_instance' op operand types must match the machine input types
  calyx.control {
  ^
calyx.mlir:42:3: note: see current operation: %1:3 = "fsm.hw_instance"(%2#1, %0#1, %arg0, %arg1, %arg2) {machine = @control, sym_name = "controller"} : (i1, i1, i1, i1, i1) -> (i1, i1, i1)
calyx.mlir:15:3: note: original machine declared here
  calyx.control {
  ^
```
I now find that this is a multi-component issue and I think I may need to run other passes, but I'm not sure, so if anyone can help me, I would appreciate it.You can see that I have no problem with the individual components below.

**Comment by rachitnigam** [comment] 2023-06-03 13:28
@linuxlonelyeagle were you able to find the cause for this issue?

**Comment by linuxlonelyeagle** [comment] 2023-06-03 13:36
> @linuxlonelyeagle were you able to find the cause for this issue?

Sorry.I really didn't find the reason for this, I just wrote the code for calyx dialect after the [code](https://docs.calyxir.org/lang/multi-component.html) for the multi-component design of the calyx project.I am not very familiar with the circt project either, and I am trying to learn through this opportunity.

**Comment by linuxlonelyeagle** [comment] 2023-06-03 13:57
> @linuxlonelyeagle were you able to find the cause for this issue?

If I have time, I will try to find this issue.

**Comment by linuxlonelyeagle** [comment] 2023-06-08 13:17
> @linuxlonelyeagle were you able to find the cause for this issue?

I have successfully detected the bug. I expect to fix the bug and submit a patch.:smiley:

**Comment by mikeurbach** [comment] 2023-06-08 22:17
Closed by https://github.com/llvm/circt/pull/5341

**Closed by mikeurbach** 2023-06-08 22:17 UTC
Labels: Calyx
