### ISSUE TITLE
[FIRRTL] OM/InnerSyms/Zero-width

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#7252] opened 2024-06-28 17:49 UTC
If you have an OMReference to a zero-width wire, when lower-to-hw runs, it drops the wire, but should error out when it needs to drop a wire with a inner symbol.  There is no construct to put the symbol on to maintain the hierpath op for OM.

Even now that HW supports zero-width types, if we used them for firrtl, this problem would still persist as there is no verilog output for a zero-width thing, so there would be no path in the output corresponding to the OMReference.

Fundamentally this was a design bug (non-deletable Reference to a zero-bit thing), but we need to catch it and error out in lower-to-hw rather than making dangling symbol references.

**Comment by youngar** [comment] 2024-06-28 18:26
Duplicate of https://github.com/llvm/circt/issues/5590

**Comment by darthscsi** [comment] 2024-07-01 15:42
closed in https://github.com/llvm/circt/commit/643571890fa0674af1b49aa98413c7babb0862b1

**Closed** 2024-07-01 15:41 UTC
Labels: bug, FIRRTL
