### ISSUE TITLE
unpacked arrays shouldn't be in RTL, or at least packed arrays should not contain unpacked arrays.

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#522] opened 2021-01-27 19:58 UTC

**Comment by teqdruid** [comment] 2021-01-27 20:05
I think there's already an issue filed to move the uarray type into the SV dialect, but I can't find it ATM.

**Comment by teqdruid** [comment] 2021-01-27 20:06
found it: #389

**Comment by lattner** [comment] 2021-01-30 06:31
Closing as a dupe of issue #389

**Closed by lattner** 2021-01-30 06:31 UTC
