### ISSUE TITLE
[Seq] SeqFIRRTLToSV Can Dramatically Expand IR Size

### ISSUE THREAD

**Issue by Siudya** [llvm/circt#4399] opened 2022-12-03 04:39 UTC
CIRCT source code tag: sifive/1/23/0
Docker: 18.06.3-ce
CIRCT Docker image was built from Ubuntu 20.04
Host OS: Centos 7.9
RAM: More than 64GiB
Generated Verilog file is extremely large in some unkown cases. Here is how to repete:

```
git clone https://github.com/OpenXiangShan/XiangShan.git
cd XiangShan
git checkout nanhu-v2
make init
mill -i XiangShan.runMain top.TopMain -td build --config DefaultConfig --full-stacktrace -X none -E chirrtl -o XSTop.chirrtl.fir --num-cores 2 --fpga-platform --disable-all --remove-assert
firtool --verilog --disable-annotation-unknown --dedup --format=fir --annotation-file=build/XSTop.anno.json -o build/XSTop.v build/XSTop.chirrtl.fir
```
The generated XSTop.v is 3.9GiB，which is 150MiB when using default firrtl compiler.

The module Ftq may be where the problem is. The size of it's verilog file is 3.8GiB, which is around 9MiB when using the default scala firrtl compiler.

**Comment by seldridge** [comment] 2022-12-03 06:42
Interesting. Thanks for the report.

Would you be able to provide the input `build/XStop.chirrtl.fir` and `build/XSTop.anno.json` files? I'm having a little trouble building this:

1. I think I need to create a `build/` directory to get around:

```
Generating MBIST_Core.csv
error
Exception in thread "main" java.io.FileNotFoundException: build/MBIST_Core.csv (No such file or directory)
```

2. Running again ran into some issue after this point:

```
Generating MBIST_L3S0.csv
Generating MBIST_L3S1.csv
Generating MBIST_L3S2.csv
Generating MBIST_L3S3.csv
1 targets failed
XiangShan.runMain subprocess failed
```

**Comment by Siudya** [comment] 2022-12-04 16:08
> Interesting. Thanks for the report.
> 
> Would you be able to provide the input `build/XStop.chirrtl.fir` and `build/XSTop.anno.json` files? I'm having a little trouble building this:
> 
>     1. I think I need to create a `build/` directory to get around:
> 
> 
> ```
> Generating MBIST_Core.csv
> error
> Exception in thread "main" java.io.FileNotFoundException: build/MBIST_Core.csv (No such file or directory)
> ```
> 
>     2. Running again after creating a build directory I ran into some issue after this point:
> 
> 
> ```
> Generating MBIST_L3S0.csv
> Generating MBIST_L3S1.csv
> Generating MBIST_L3S2.csv
> Generating MBIST_L3S3.csv
> 1 targets failed
> XiangShan.runMain subprocess failed
> ```

[bug_report.tar.txt](https://github.com/llvm/circt/files/10148973/bug_report.tar.txt)
Generating the .fir file needs more than 32GiB RAM while 64GiB is better.
Here is the generated files. Please rename the suffix of the attachment to ".tar.bz2".

**Comment by seldridge** [comment] 2022-12-04 23:01
I can reproduce. Yes, the coding style in `NewFTQ.scala` is causing problems. This is creating one incredibly long if/else chain which results it in being, by-far, the largest output Verilog module:

```
# l -S issues/4399/mfc       
total 3200480
-rw-r--r--     1 schuylere  staff   1.4G Dec  4 17:14 Ftq.sv
-rw-r--r--     1 schuylere  staff   8.3M Dec  4 16:57 XSCore.sv
-rw-r--r--     1 schuylere  staff   4.4M Dec  4 16:57 LoadQueue.sv
```

All the assignments to `commitStateQueue` seem to be causing some issue where CIRCT is preserving these as opposed to canonicalization them into a simpler structure. This `commitStateQueue` looks like a 2-bit vector of size 64x16. This is then assigned in a several different blocks using subaccesses. Just one of these vector elements produces ~16k different assignments in the output verilog. This can likely be fixed with a different coding style inside `NewFTQ.scala`. However, this also indicates that CIRCT should do better on this code example.

An example of the Verilog output for one vector entry is the following. Somebody might have an idea on exactly what is missing here:

```verilog
          if (_GEN_19243 & _GEN_20345 | _GEN_19245)     // NewFtq.scala:1005:63, :1009:71
            commitStateQueue_0_0 <= 2'h2;       // Mux.scala:47:70, NewFtq.scala:565:33
          else if (io_fromBackend_rob_commits_4_valid) begin
            if (_T_459) begin   // NewFtq.scala:1008:31
              if (_GEN_17029)   // NewFtq.scala:1005:63, :1009:71
                commitStateQueue_0_0 <= 2'h2;   // Mux.scala:47:70, NewFtq.scala:565:33
              else if (io_fromBackend_rob_commits_3_valid) begin
                if (_T_451) begin       // NewFtq.scala:1008:31
                  if (_GEN_13721)       // NewFtq.scala:1005:63, :1009:71
                    commitStateQueue_0_0 <= 2'h2;       // Mux.scala:47:70, NewFtq.scala:565:33
                  else if (io_fromBackend_rob_commits_2_valid) begin
                    if (_T_443) begin   // NewFtq.scala:1008:31
                      if (_GEN_10413)   // NewFtq.scala:1005:63, :1009:71
                        commitStateQueue_0_0 <= 2'h2;   // Mux.scala:47:70, NewFtq.scala:565:33
                      else if (io_fromBackend_rob_commits_1_valid) begin
                        if (_T_435) begin       // NewFtq.scala:1008:31
                          if (_GEN_7105)        // NewFtq.scala:1005:63, :1009:71
                            commitStateQueue_0_0 <= 2'h2;       // Mux.scala:47:70, NewFtq.scala:565:33
                          else if (io_fromBackend_rob_commits_0_valid) begin
                            if (_T_427) begin   // NewFtq.scala:1008:31
                              if (_GEN_3797)    // NewFtq.scala:1005:63, :1009:71
                                commitStateQueue_0_0 <= 2'h2;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_1670)       // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                              else if (_GEN_579)        // NewFtq.scala:806:23, :811:{32,37}
                                commitStateQueue_0_0 <= 2'h1;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_389)        // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                            end
                            else if (_T_430) begin      // NewFtq.scala:1010:36
                              if (_GEN_4836)    // NewFtq.scala:1005:63, :1011:71
                                commitStateQueue_0_0 <= 2'h2;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_1670)       // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                              else if (_GEN_579)        // NewFtq.scala:806:23, :811:{32,37}
                                commitStateQueue_0_0 <= 2'h1;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_389)        // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                            end
                            else if (_GEN_5042) // NewFtq.scala:1005:63, :1012:45, :1014:36
                              commitStateQueue_0_0 <= 2'h2;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_1670) // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                            else if (_GEN_579)  // NewFtq.scala:806:23, :811:{32,37}
                              commitStateQueue_0_0 <= 2'h1;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_389)  // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                          end
                          else if (_GEN_1670)   // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                            commitStateQueue_0_0 <= 2'h0;       // NewFtq.scala:565:33
                          else if (_GEN_579)    // NewFtq.scala:806:23, :811:{32,37}
                            commitStateQueue_0_0 <= 2'h1;       // Mux.scala:47:70, NewFtq.scala:565:33
                          else if (_GEN_389)    // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                            commitStateQueue_0_0 <= 2'h0;       // NewFtq.scala:565:33
                        end
                        else if (_T_438) begin  // NewFtq.scala:1010:36
                          if (_GEN_8144)        // NewFtq.scala:1005:63, :1011:71
                            commitStateQueue_0_0 <= 2'h2;       // Mux.scala:47:70, NewFtq.scala:565:33
                          else if (io_fromBackend_rob_commits_0_valid) begin
                            if (_T_427) begin   // NewFtq.scala:1008:31
                              if (_GEN_3797)    // NewFtq.scala:1005:63, :1009:71
                                commitStateQueue_0_0 <= 2'h2;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_1670)       // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                              else if (_GEN_579)        // NewFtq.scala:806:23, :811:{32,37}
                                commitStateQueue_0_0 <= 2'h1;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_389)        // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                            end
                            else if (_T_430) begin      // NewFtq.scala:1010:36
                              if (_GEN_4836)    // NewFtq.scala:1005:63, :1011:71
                                commitStateQueue_0_0 <= 2'h2;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_1670)       // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                              else if (_GEN_579)        // NewFtq.scala:806:23, :811:{32,37}
                                commitStateQueue_0_0 <= 2'h1;   // Mux.scala:47:70, NewFtq.scala:565:33
                              else if (_GEN_389)        // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                                commitStateQueue_0_0 <= 2'h0;   // NewFtq.scala:565:33
                            end
                            else if (_GEN_5042) // NewFtq.scala:1005:63, :1012:45, :1014:36
                              commitStateQueue_0_0 <= 2'h2;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_1670) // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                            else if (_GEN_579)  // NewFtq.scala:806:23, :811:{32,37}
                              commitStateQueue_0_0 <= 2'h1;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_389)  // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                          end
                          else if (_GEN_1670)   // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                            commitStateQueue_0_0 <= 2'h0;       // NewFtq.scala:565:33
                          else if (_GEN_579)    // NewFtq.scala:806:23, :811:{32,37}
                            commitStateQueue_0_0 <= 2'h1;       // Mux.scala:47:70, NewFtq.scala:565:33
                          else if (_GEN_389)    // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                            commitStateQueue_0_0 <= 2'h0;       // NewFtq.scala:565:33
                        end
                        else if (_GEN_8350)     // NewFtq.scala:1005:63, :1012:45, :1014:36
                          commitStateQueue_0_0 <= 2'h2; // Mux.scala:47:70, NewFtq.scala:565:33
                        else if (io_fromBackend_rob_commits_0_valid) begin
                          if (_T_427) begin     // NewFtq.scala:1008:31
                            if (_GEN_3797)      // NewFtq.scala:1005:63, :1009:71
                              commitStateQueue_0_0 <= 2'h2;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_1670) // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                            else if (_GEN_579)  // NewFtq.scala:806:23, :811:{32,37}
                              commitStateQueue_0_0 <= 2'h1;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_389)  // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                          end
                          else if (_T_430) begin        // NewFtq.scala:1010:36
                            if (_GEN_4836)      // NewFtq.scala:1005:63, :1011:71
                              commitStateQueue_0_0 <= 2'h2;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_1670) // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                            else if (_GEN_579)  // NewFtq.scala:806:23, :811:{32,37}
                              commitStateQueue_0_0 <= 2'h1;     // Mux.scala:47:70, NewFtq.scala:565:33
                            else if (_GEN_389)  // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                              commitStateQueue_0_0 <= 2'h0;     // NewFtq.scala:565:33
                          end
                          else if (_GEN_5042)   // NewFtq.scala:1005:63, :1012:45, :1014:36
                            commitStateQueue_0_0 <= 2'h2;       // Mux.scala:47:70, NewFtq.scala:565:33
                          else if (_GEN_1670)   // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                            commitStateQueue_0_0 <= 2'h0;       // NewFtq.scala:565:33
                          else if (_GEN_579)    // NewFtq.scala:806:23, :811:{32,37}
                            commitStateQueue_0_0 <= 2'h1;       // Mux.scala:47:70, NewFtq.scala:565:33
                          else if (_GEN_389)    // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                            commitStateQueue_0_0 <= 2'h0;       // NewFtq.scala:565:33
                        end
                        else if (_GEN_1670)     // NewFtq.scala:978:51, :989:19, :991:60, :992:13
                          commitStateQueue_0_0 <= 2'h0; // NewFtq.scala:565:33
                        else if (_GEN_579)      // NewFtq.scala:806:23, :811:{32,37}
                          commitStateQueue_0_0 <= 2'h1; // Mux.scala:47:70, NewFtq.scala:565:33
                        else if (_GEN_389)      // 610:54:611:49, NewFtq.scala:565:33, NewFtq.scala 606:17:565:33
                          commitStateQueue_0_0 <= 2'h0; // NewFtq.scala:565:33
                      end
```

**Comment by seldridge** [comment] 2022-12-04 23:47
Alright, I think I have a somewhat minimal example. The problem is in the `SeqFIRRTLToSV` pass. This causes a massive blowup in IR size. A FIRRTL-level example is the following:

```
circuit Foo :
  module Foo :
    input clock : Clock
    input reset : UInt<1>
    input a : UInt<1>[16]
    input index : UInt<2>
    output b : UInt<1>[16]

    reg r : UInt<2>[16], clock with :
      reset => (UInt<1>("h0"), r) 
    when a[0] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[1] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[2] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[3] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[4] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[5] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[6] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[7] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[8] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[9] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[10] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[11] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[12] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[13] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[14] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    when a[15] : 
      r[index] <= UInt<1>("h1") 
    else :
      r[index] <= UInt<2>("h2") 
    b <= r 
```

When compiled with the MFC, this produces a 70MiB Verilog file. When compiled with the SFC, this produces a 68KiB Verilog file.

You can reproduce this error just by running the following `.mlir` through `circt-opt -lower-seq-firrtl-to-sv`:

```mlir
module {
  hw.module @Foo(%clock: i1, %reset: i1, %a_0: i1, %a_1: i1, %a_2: i1, %a_3: i1, %a_4: i1, %a_5: i1, %a_6: i1, %a_7: i1, %a_8: i1, %a_9: i1, %a_10: i1, %a_11: i1, %a_12: i1, %a_13: i1, %a_14: i1, %a_15: i1, %index: i2) -> (b_0: i1, b_1: i1, b_2: i1, b_3: i1, b_4: i1, b_5: i1, b_6: i1, b_7: i1, b_8: i1, b_9: i1, b_10: i1, b_11: i1, b_12: i1, b_13: i1, b_14: i1, b_15: i1) {
    %false = hw.constant false
    %c0_i2 = hw.constant 0 : i2
    %c-1_i2 = hw.constant -1 : i2
    %c-2_i2 = hw.constant -2 : i2
    %c1_i2 = hw.constant 1 : i2
    %r_0 = seq.firreg %189 clock %clock {firrtl.random_init_start = 0 : ui64} : i2
    %r_1 = seq.firreg %191 clock %clock {firrtl.random_init_start = 2 : ui64} : i2
    %r_2 = seq.firreg %193 clock %clock {firrtl.random_init_start = 4 : ui64} : i2
    %r_3 = seq.firreg %195 clock %clock {firrtl.random_init_start = 6 : ui64} : i2
    %0 = comb.icmp eq %index, %c0_i2 : i2
    %1 = comb.mux bin %0, %c1_i2, %r_0 : i2
    %2 = comb.icmp eq %index, %c1_i2 : i2
    %3 = comb.mux bin %2, %c1_i2, %r_1 : i2
    %4 = comb.icmp eq %index, %c-2_i2 : i2
    %5 = comb.mux bin %4, %c1_i2, %r_2 : i2
    %6 = comb.icmp eq %index, %c-1_i2 : i2
    %7 = comb.mux bin %6, %c1_i2, %r_3 : i2
    %8 = comb.mux bin %0, %c-2_i2, %r_0 : i2
    %9 = comb.mux bin %a_0, %1, %8 : i2
    %10 = comb.mux bin %2, %c-2_i2, %r_1 : i2
    %11 = comb.mux bin %a_0, %3, %10 : i2
    %12 = comb.mux bin %4, %c-2_i2, %r_2 : i2
    %13 = comb.mux bin %a_0, %5, %12 : i2
    %14 = comb.mux bin %6, %c-2_i2, %r_3 : i2
    %15 = comb.mux bin %a_0, %7, %14 : i2
    %16 = comb.mux bin %0, %c1_i2, %9 : i2
    %17 = comb.mux bin %2, %c1_i2, %11 : i2
    %18 = comb.mux bin %4, %c1_i2, %13 : i2
    %19 = comb.mux bin %6, %c1_i2, %15 : i2
    %20 = comb.mux bin %0, %c-2_i2, %9 : i2
    %21 = comb.mux bin %a_1, %16, %20 : i2
    %22 = comb.mux bin %2, %c-2_i2, %11 : i2
    %23 = comb.mux bin %a_1, %17, %22 : i2
    %24 = comb.mux bin %4, %c-2_i2, %13 : i2
    %25 = comb.mux bin %a_1, %18, %24 : i2
    %26 = comb.mux bin %6, %c-2_i2, %15 : i2
    %27 = comb.mux bin %a_1, %19, %26 : i2
    %28 = comb.mux bin %0, %c1_i2, %21 : i2
    %29 = comb.mux bin %2, %c1_i2, %23 : i2
    %30 = comb.mux bin %4, %c1_i2, %25 : i2
    %31 = comb.mux bin %6, %c1_i2, %27 : i2
    %32 = comb.mux bin %0, %c-2_i2, %21 : i2
    %33 = comb.mux bin %a_2, %28, %32 : i2
    %34 = comb.mux bin %2, %c-2_i2, %23 : i2
    %35 = comb.mux bin %a_2, %29, %34 : i2
    %36 = comb.mux bin %4, %c-2_i2, %25 : i2
    %37 = comb.mux bin %a_2, %30, %36 : i2
    %38 = comb.mux bin %6, %c-2_i2, %27 : i2
    %39 = comb.mux bin %a_2, %31, %38 : i2
    %40 = comb.mux bin %0, %c1_i2, %33 : i2
    %41 = comb.mux bin %2, %c1_i2, %35 : i2
    %42 = comb.mux bin %4, %c1_i2, %37 : i2
    %43 = comb.mux bin %6, %c1_i2, %39 : i2
    %44 = comb.mux bin %0, %c-2_i2, %33 : i2
    %45 = comb.mux bin %a_3, %40, %44 : i2
    %46 = comb.mux bin %2, %c-2_i2, %35 : i2
    %47 = comb.mux bin %a_3, %41, %46 : i2
    %48 = comb.mux bin %4, %c-2_i2, %37 : i2
    %49 = comb.mux bin %a_3, %42, %48 : i2
    %50 = comb.mux bin %6, %c-2_i2, %39 : i2
    %51 = comb.mux bin %a_3, %43, %50 : i2
    %52 = comb.mux bin %0, %c1_i2, %45 : i2
    %53 = comb.mux bin %2, %c1_i2, %47 : i2
    %54 = comb.mux bin %4, %c1_i2, %49 : i2
    %55 = comb.mux bin %6, %c1_i2, %51 : i2
    %56 = comb.mux bin %0, %c-2_i2, %45 : i2
    %57 = comb.mux bin %a_4, %52, %56 : i2
    %58 = comb.mux bin %2, %c-2_i2, %47 : i2
    %59 = comb.mux bin %a_4, %53, %58 : i2
    %60 = comb.mux bin %4, %c-2_i2, %49 : i2
    %61 = comb.mux bin %a_4, %54, %60 : i2
    %62 = comb.mux bin %6, %c-2_i2, %51 : i2
    %63 = comb.mux bin %a_4, %55, %62 : i2
    %64 = comb.mux bin %0, %c1_i2, %57 : i2
    %65 = comb.mux bin %2, %c1_i2, %59 : i2
    %66 = comb.mux bin %4, %c1_i2, %61 : i2
    %67 = comb.mux bin %6, %c1_i2, %63 : i2
    %68 = comb.mux bin %0, %c-2_i2, %57 : i2
    %69 = comb.mux bin %a_5, %64, %68 : i2
    %70 = comb.mux bin %2, %c-2_i2, %59 : i2
    %71 = comb.mux bin %a_5, %65, %70 : i2
    %72 = comb.mux bin %4, %c-2_i2, %61 : i2
    %73 = comb.mux bin %a_5, %66, %72 : i2
    %74 = comb.mux bin %6, %c-2_i2, %63 : i2
    %75 = comb.mux bin %a_5, %67, %74 : i2
    %76 = comb.mux bin %0, %c1_i2, %69 : i2
    %77 = comb.mux bin %2, %c1_i2, %71 : i2
    %78 = comb.mux bin %4, %c1_i2, %73 : i2
    %79 = comb.mux bin %6, %c1_i2, %75 : i2
    %80 = comb.mux bin %0, %c-2_i2, %69 : i2
    %81 = comb.mux bin %a_6, %76, %80 : i2
    %82 = comb.mux bin %2, %c-2_i2, %71 : i2
    %83 = comb.mux bin %a_6, %77, %82 : i2
    %84 = comb.mux bin %4, %c-2_i2, %73 : i2
    %85 = comb.mux bin %a_6, %78, %84 : i2
    %86 = comb.mux bin %6, %c-2_i2, %75 : i2
    %87 = comb.mux bin %a_6, %79, %86 : i2
    %88 = comb.mux bin %0, %c1_i2, %81 : i2
    %89 = comb.mux bin %2, %c1_i2, %83 : i2
    %90 = comb.mux bin %4, %c1_i2, %85 : i2
    %91 = comb.mux bin %6, %c1_i2, %87 : i2
    %92 = comb.mux bin %0, %c-2_i2, %81 : i2
    %93 = comb.mux bin %a_7, %88, %92 : i2
    %94 = comb.mux bin %2, %c-2_i2, %83 : i2
    %95 = comb.mux bin %a_7, %89, %94 : i2
    %96 = comb.mux bin %4, %c-2_i2, %85 : i2
    %97 = comb.mux bin %a_7, %90, %96 : i2
    %98 = comb.mux bin %6, %c-2_i2, %87 : i2
    %99 = comb.mux bin %a_7, %91, %98 : i2
    %100 = comb.mux bin %0, %c1_i2, %93 : i2
    %101 = comb.mux bin %2, %c1_i2, %95 : i2
    %102 = comb.mux bin %4, %c1_i2, %97 : i2
    %103 = comb.mux bin %6, %c1_i2, %99 : i2
    %104 = comb.mux bin %0, %c-2_i2, %93 : i2
    %105 = comb.mux bin %a_8, %100, %104 : i2
    %106 = comb.mux bin %2, %c-2_i2, %95 : i2
    %107 = comb.mux bin %a_8, %101, %106 : i2
    %108 = comb.mux bin %4, %c-2_i2, %97 : i2
    %109 = comb.mux bin %a_8, %102, %108 : i2
    %110 = comb.mux bin %6, %c-2_i2, %99 : i2
    %111 = comb.mux bin %a_8, %103, %110 : i2
    %112 = comb.mux bin %0, %c1_i2, %105 : i2
    %113 = comb.mux bin %2, %c1_i2, %107 : i2
    %114 = comb.mux bin %4, %c1_i2, %109 : i2
    %115 = comb.mux bin %6, %c1_i2, %111 : i2
    %116 = comb.mux bin %0, %c-2_i2, %105 : i2
    %117 = comb.mux bin %a_9, %112, %116 : i2
    %118 = comb.mux bin %2, %c-2_i2, %107 : i2
    %119 = comb.mux bin %a_9, %113, %118 : i2
    %120 = comb.mux bin %4, %c-2_i2, %109 : i2
    %121 = comb.mux bin %a_9, %114, %120 : i2
    %122 = comb.mux bin %6, %c-2_i2, %111 : i2
    %123 = comb.mux bin %a_9, %115, %122 : i2
    %124 = comb.mux bin %0, %c1_i2, %117 : i2
    %125 = comb.mux bin %2, %c1_i2, %119 : i2
    %126 = comb.mux bin %4, %c1_i2, %121 : i2
    %127 = comb.mux bin %6, %c1_i2, %123 : i2
    %128 = comb.mux bin %0, %c-2_i2, %117 : i2
    %129 = comb.mux bin %a_10, %124, %128 : i2
    %130 = comb.mux bin %2, %c-2_i2, %119 : i2
    %131 = comb.mux bin %a_10, %125, %130 : i2
    %132 = comb.mux bin %4, %c-2_i2, %121 : i2
    %133 = comb.mux bin %a_10, %126, %132 : i2
    %134 = comb.mux bin %6, %c-2_i2, %123 : i2
    %135 = comb.mux bin %a_10, %127, %134 : i2
    %136 = comb.mux bin %0, %c1_i2, %129 : i2
    %137 = comb.mux bin %2, %c1_i2, %131 : i2
    %138 = comb.mux bin %4, %c1_i2, %133 : i2
    %139 = comb.mux bin %6, %c1_i2, %135 : i2
    %140 = comb.mux bin %0, %c-2_i2, %129 : i2
    %141 = comb.mux bin %a_11, %136, %140 : i2
    %142 = comb.mux bin %2, %c-2_i2, %131 : i2
    %143 = comb.mux bin %a_11, %137, %142 : i2
    %144 = comb.mux bin %4, %c-2_i2, %133 : i2
    %145 = comb.mux bin %a_11, %138, %144 : i2
    %146 = comb.mux bin %6, %c-2_i2, %135 : i2
    %147 = comb.mux bin %a_11, %139, %146 : i2
    %148 = comb.mux bin %0, %c1_i2, %141 : i2
    %149 = comb.mux bin %2, %c1_i2, %143 : i2
    %150 = comb.mux bin %4, %c1_i2, %145 : i2
    %151 = comb.mux bin %6, %c1_i2, %147 : i2
    %152 = comb.mux bin %0, %c-2_i2, %141 : i2
    %153 = comb.mux bin %a_12, %148, %152 : i2
    %154 = comb.mux bin %2, %c-2_i2, %143 : i2
    %155 = comb.mux bin %a_12, %149, %154 : i2
    %156 = comb.mux bin %4, %c-2_i2, %145 : i2
    %157 = comb.mux bin %a_12, %150, %156 : i2
    %158 = comb.mux bin %6, %c-2_i2, %147 : i2
    %159 = comb.mux bin %a_12, %151, %158 : i2
    %160 = comb.mux bin %0, %c1_i2, %153 : i2
    %161 = comb.mux bin %2, %c1_i2, %155 : i2
    %162 = comb.mux bin %4, %c1_i2, %157 : i2
    %163 = comb.mux bin %6, %c1_i2, %159 : i2
    %164 = comb.mux bin %0, %c-2_i2, %153 : i2
    %165 = comb.mux bin %a_13, %160, %164 : i2
    %166 = comb.mux bin %2, %c-2_i2, %155 : i2
    %167 = comb.mux bin %a_13, %161, %166 : i2
    %168 = comb.mux bin %4, %c-2_i2, %157 : i2
    %169 = comb.mux bin %a_13, %162, %168 : i2
    %170 = comb.mux bin %6, %c-2_i2, %159 : i2
    %171 = comb.mux bin %a_13, %163, %170 : i2
    %172 = comb.mux bin %0, %c1_i2, %165 : i2
    %173 = comb.mux bin %2, %c1_i2, %167 : i2
    %174 = comb.mux bin %4, %c1_i2, %169 : i2
    %175 = comb.mux bin %6, %c1_i2, %171 : i2
    %176 = comb.mux bin %0, %c-2_i2, %165 : i2
    %177 = comb.mux bin %a_14, %172, %176 : i2
    %178 = comb.mux bin %2, %c-2_i2, %167 : i2
    %179 = comb.mux bin %a_14, %173, %178 : i2
    %180 = comb.mux bin %4, %c-2_i2, %169 : i2
    %181 = comb.mux bin %a_14, %174, %180 : i2
    %182 = comb.mux bin %6, %c-2_i2, %171 : i2
    %183 = comb.mux bin %a_14, %175, %182 : i2
    %184 = comb.mux bin %0, %c1_i2, %177 : i2
    %185 = comb.mux bin %2, %c1_i2, %179 : i2
    %186 = comb.mux bin %4, %c1_i2, %181 : i2
    %187 = comb.mux bin %6, %c1_i2, %183 : i2
    %188 = comb.mux bin %0, %c-2_i2, %177 : i2
    %189 = comb.mux bin %a_15, %184, %188 : i2
    %190 = comb.mux bin %2, %c-2_i2, %179 : i2
    %191 = comb.mux bin %a_15, %185, %190 : i2
    %192 = comb.mux bin %4, %c-2_i2, %181 : i2
    %193 = comb.mux bin %a_15, %186, %192 : i2
    %194 = comb.mux bin %6, %c-2_i2, %183 : i2
    %195 = comb.mux bin %a_15, %187, %194 : i2
    %196 = comb.extract %r_0 from 0 : (i2) -> i1
    %197 = comb.extract %r_1 from 0 : (i2) -> i1
    %198 = comb.extract %r_2 from 0 : (i2) -> i1
    %199 = comb.extract %r_3 from 0 : (i2) -> i1
    hw.output %196, %197, %198, %199, %false, %false, %false, %false, %false, %false, %false, %false, %false, %false, %false, %false : i1, i1, i1, i1, i1, i1, i1, i1, i1, i1, i1, i1, i1, i1, i1, i1
  }
}
```

After this one pass, this is 200MiB of `.mlir`.

**Comment by Siudya** [comment] 2022-12-05 02:54
Indeed, I can reproduce with your minimal case. These structures can be summarized as follows: 
A big matrix or vector consists of small elements, each of which is with a mux chain (an independent write condition may be just enough ?) connected to its D port.
Such a structure is neccessary in our design when storing meta data written by multiple paths. 
According to your example, it seems that even a small vector with respectively few and short write paths to its elements can trigger this problem. It brings difficulties to physical design and RTL verification.
Is there any workaround I can try, or I have to keep using SFC for now?

**Comment by seldridge** [comment] 2022-12-05 04:29
I don't have a workaround right now. 😅 This is clearly a bug... I expect this will get fixed this week.

We've seen problems with this pass before and had to back out changes to it. Relevant commits:
- 101115452e7ceba6c00d5fc5f02541c24abb2719
- 6380c594bfa35cb3aec35800e0bb7fe6088c1bf4

I think @nandor or @darthscsi may have an idea on a course of action.

**Comment by uenoku** [comment] 2022-12-05 07:05
The exponential IR is caused by constructing if-else trees for mux register updates. SFC does the same thing but it seems SFC restricts the mux depth:
https://github.com/chipsalliance/firrtl/blob/4f3d1003811aa38d10e32b347c8607414d9be034/src/main/scala/firrtl/transforms/FlattenRegUpdate.scala#L86

**Comment by darthscsi** [comment] 2022-12-05 19:32
Small canonicalizer and it reduces to:
```
  always @(posedge clock) begin
    automatic logic [1:0] _GEN = a_15 ? 2'h1 : 2'h2;
    r_0 <= index == 2'h0 ? _GEN : r_0;
    r_1 <= index == 2'h1 ? _GEN : r_1;
    r_2 <= index == 2'h2 ? _GEN : r_2;
    r_3 <= (&index) ? _GEN : r_3;
  end // always @(posedge)
```

**Comment by darthscsi** [comment] 2022-12-05 22:07
with https://github.com/llvm/circt/pull/4405 the test case is 89M
```
~/sifive/circt/tmp/bug_report$ du -hs v2
96M	v2
```

**Comment by darthscsi** [comment] 2022-12-05 23:11
Seems pretty well addressed by #4403 and #4405

**Closed by darthscsi** 2022-12-05 23:11 UTC
Labels: seq
