### ISSUE TITLE
MemOp with readwrite ports not lowered

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#669] opened 2021-02-24 22:31 UTC
from firtool:
```
foo.mlir:1759866:79: error: 'firrtl.mem' op readwrite ports should be lowered into separate read and write ports by previous passes
```

**Comment by seldridge** [comment] 2021-02-24 23:25
Dupe of https://github.com/llvm/circt/issues/480. Closing in favor of tracking there.

**Closed by seldridge** 2021-02-24 23:25 UTC
