### ISSUE TITLE
CI Cache Misses on GCC Debug Builds

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#4303] opened 2022-11-13 21:33 UTC
I'm seeing a lot of unexpected cache misses on GCC Debug builds. E.g.: 

- This takes 2+ hours: https://github.com/llvm/circt/actions/runs/3456217534/jobs/5768801773 and takes a cache miss
- This takes ~10 minutes: https://github.com/llvm/circt/actions/runs/3456217534/jobs/5768801723 and takes a cache hit

**Comment by teqdruid** [comment] 2022-11-13 23:39
Duplicate of #4300

**Comment by seldridge** [comment] 2022-11-14 00:19
Closing this as it's a duplicate. Thanks for the pointer John!

**Closed** 2022-11-14 00:19 UTC
