### ISSUE TITLE
[FIRRTL] (dshl) error

### ISSUE THREAD

**Issue by drom** [llvm/circt#428] opened 2021-01-12 00:25 UTC
The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    input inp_1: UInt<1>
    input inp_2: SInt<5>
    output tmp9: SInt<3>
    tmp9 <= dshl(inp_2, inp_1)
```

Compiled with `firtool --lower-to-rtl` gives an error:

```mlir
a_top_mod.fir:6:10: error: destination width 3 is not greater than or equal to source width 6
    tmp9 <= dshl(inp_2, inp_1)
         ^
a_top_mod.fir:6:10: note: see current operation: "firrtl.connect"(%tmp9, %0) : (!firrtl.flip<sint<3>>, !firrtl.sint<6>) -> ()
```

Compiled with `firrtl-1.4.0` produces this Verilog:

```verilog
module top_mod(
  input        inp_1,
  input  [4:0] inp_2,
  output [2:0] tmp9
);
  wire [5:0] _GEN_0 = {{1{inp_2[4]}},inp_2};
  wire [5:0] _GEN_1 = $signed(_GEN_0) << inp_1;
  assign tmp9 = _GEN_1[2:0];
endmodule
```

**Comment by darthscsi** [comment] 2021-01-14 15:42
According to the firrtl spec 7.14, this isn't a valid result type for dshl ( it should be 6).  The question is what to do with the implicit truncation.

**Comment by seldridge** [comment] 2021-01-14 16:59
I don't think there's anything going on with `dshl`, more that the SFC treats connect as having partial connect width truncation semantics: https://github.com/llvm/circt/issues/423.

**Comment by seldridge** [comment] 2021-01-14 17:37
Correction, there's something weird going on with `dshl` and possibly other ops where the SFC's `Legalize` pass is also adding casting. I'm trying to figure out what's going on.

**Comment by seldridge** [comment] 2021-01-14 17:57
Further correction: there's nothing wrong with the SFC here. The SFC blindly adds casts in this situation, but only because it already type checked `tmp <= dshl(...)`. I think this is then a duplicate of #423.

**Comment by lattner** [comment] 2021-01-14 23:14
Are we implementing dshl correctly?  It isn't in the firrtl spec so I took a guess at the result of the width and lowering.

**Comment by seldridge** [comment] 2021-01-15 04:35
`dshl` looks a-okay. And while that _is_ in the spec, I think you're thinking of the undocumented `dshlw`. That should only show up in "optimized low FIRRTL" and is an artifact of making the FIRRTL IR to Verilog mapping easier because FIRRTL and Verilog disagree about width behavior (life is very hard when you don't have multiple IRs... 😃).

**Comment by lattner** [comment] 2021-01-15 05:41
Yeah you're right I was thinking of dshlw.  Is it ok? :-)

**Closed** 2021-01-22 21:35 UTC
Labels: FIRRTL
