### ISSUE TITLE
[FIRRTL] Parsing broken for "an instance called module"

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#4564] opened 2023-01-20 23:43 UTC
FIRRTL parsing is broken for the following circuit:

```
circuit Foo:
  module Bar:
    skip

  module Foo:

    inst module of Bar
```

The parser thinks that `module` has to be the first token when it can be an identifier:

```
build/Bar.fir:7:10: error: 'module' must be first token on its line
    inst module of Bar
         ^
```

h/t @chick for finding this one.

**Comment by youngar** [comment] 2023-01-24 18:18
dupe of https://github.com/llvm/circt/issues/3363

**Closed** 2023-03-08 20:42 UTC
Labels: bug, FIRRTL
